name: Deploy to GitHub Pages

on:
  push:
    branches: [ gh-pages ]  # Branch que contém o código do site
  workflow_dispatch:  # Permite acionar manualmente

permissions:
  contents: write
  pages: write
  id-token: write

# Permite que apenas uma implantação em andamento + 1 na fila
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci

      - name: Build Frontend
        run: |
          # Apenas constrói o frontend
          cd client
          npm run build
          # Cria um arquivo .nojekyll para desativar o processamento Jekyll
          touch dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Caminho para os arquivos estáticos gerados (dentro da pasta client)
          path: 'client/dist/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
